import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import cn from "classnames";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { FavoritesProvider } from "./hooks/useFavorites";
import { AuthProvider } from "./hooks/useAuth";
import Modal from "./components/Modal";
import { AdoptionRequestsProvider } from "./hooks/useAdoptionRequest";
import { ModalProvider } from "./hooks/useModal";
import "./globals.css";

const poppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["700", "600"],
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-MX">
      <body
        className={cn(
          interFont.variable,
          poppinsFont.variable,
          "antialiased",
          "bg-background",
          "text-gray-primary"
        )}
      >
        <AuthProvider>
          <FavoritesProvider>
            <AdoptionRequestsProvider>
              <ModalProvider>
                <Header />
                {children}
                <Footer />
                <Modal />
                {/* <DefaultLayout>{children}</DefaultLayout> */}
              </ModalProvider>
            </AdoptionRequestsProvider>
          </FavoritesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
